### ISSUE TITLE
how to use localhost run

### ISSUE THREAD

**Issue by xprabhudayal** [buidai123/Kaggle_VSCode_Remote_SSH#2]
hi,
im interested in contributing to your project, is there any way we can integrate localhost.run into it as ngrok is queit costly

**Comment by buidai123** [comment]
hi, i've taken a quick look at localhost.run and from what i can see, it primarily offers HTTP and TLS tunnels, but seems like it don't have TCP tunneling for ssh connections right?

That said, i may have missed something in my glance, if you're aware of any its features that could support SSH connection, i'd be very intersted to learn more

but i've recently discovered an open-source alternative to ngrok called zrok. it seems promissing as it's free to use, don't require a creadit card with fewer limitations compared to ngrok's free tire, i've been busy lately, havn't had a chance to really test it out yet. But i'm planning to give it a try soon.

**Comment by xprabhudayal** [comment]
Maybe if possible, I'll check it out ...
